### PR TITLE
chore(deps): update versions of typescript and karma

### PR DESCRIPTION
**Pull request by waitingsong**

### CODE REVIEW

**Comment by erikbarke** [comment]
Hey @waitingsong, thanks!

This upgrade breaks the integration tests:

```bash
> tests-integration-latest@3.0.13 dev:ci /home/travis/build/monounity/karma-typescript/tests/integration-latest
> gulp dev:ci --cwd . && karma start --browsers ChromeHeadless --single-run
[11:27:18] Using gulpfile ~/build/monounity/karma-typescript/gulpfile.js
[11:27:18] Starting 'clean'...
[11:27:18] Starting 'copy'...
[11:27:18] Finished 'clean' after 9.91 ms
[11:27:18] Finished 'copy' after 73 ms
[11:27:18] Starting 'dev:ci'...
[11:27:18] Finished 'dev:ci' after 23 μs
20 08 2018 11:27:21.831:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.0.1
20 08 2018 11:27:30.940:ERROR [compiler.karma-typescript]: node_modules/@types/node/index.d.ts(686,14): error TS2484: Export declaration conflicts with exported declaration of 'Buffer'.
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.14.4/bin/node" "/home/travis/.nvm/versions/node/v6.14.4/bin/npm" "run" "dev:ci"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tests-integration-latest@3.0.13 dev:ci: `gulp dev:ci --cwd . && karma start --browsers ChromeHeadless --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tests-integration-latest@3.0.13 dev:ci script 'gulp dev:ci --cwd . && karma start --browsers ChromeHeadless --single-run'.
```
It seems like a simple typings mismatch, do you get this error on your end too?

**Comment by waitingsong** [comment]
@erikbarke  It works without such issue with my project .

**Comment by erikbarke** [comment]
But are you able to run the integration tests without errors on your end?

[Contributing Guideines](https://github.com/monounity/karma-typescript/wiki/Contributing)

**Comment by erikbarke** [comment]
Closing in favor of #292

**Pull request closed without merging**
