### PR TITLE
Feature/relative path

### LINKED ISSUE #188: Provide relative path to instrumenter exclude regex
Hello,

`Coverage.prototype.isExcluded = function (regex, path)` receives the full path of files. This may be inapropriate in certain situations. For example, suppose I want to ignore the `test/` folder from my project. Currently, the only option is to set 
```
karmaTypescriptConfig: {
	coverageOptions: {
		exclude: [
			/test(\/|\\)/,
		]
	}
}
```
in my `karma.conf.js`.

This works fine unless a parent folder of the project's root directory is named `test`. If that happens, the regex will match all files and the coverage report will be empty. I just had the issue today where one of the parent project directory name contained the word "test".

In `coverage.js:31`, instead of passing `file.originalPath` to `isExcluded`, a path relative to the project's root directory would probably be more suitable.

What do you think ?

All the best;

### PR DESCRIPTION
**Pull request by gempain**
Fixes #188 

@erikbarke 

Tests are passing on my side, but I could not find how to setup unit tests to ensure breaking changes check in the future.

I also ignored a few directories to lighten the repo. However, I think it would be nice to add a script to run tests more easily. Currently, for source changes to be reflected on the tests, you need to re-run `npm run build` and `npm run build:ci` (I haven't figured out whether both scripts need to be run, so I just ran them both to be sure). The development test workflow should probably be made more clear to future contributors.

All the best;

### CODE REVIEW

**Comment by erikbarke** [comment]
Hey thanks 😄

I've started a new wiki page with simple guidelines, as per your suggestion: [Contributing](https://github.com/monounity/karma-typescript/wiki/Contributing)

The build for this PR broke on both of the build servers (the linter barfs about formatting and the unit tests crash), I hope the new guidelines help.

**Comment by gempain** [comment]
Very welcome :) Sorry I couldn't find the page you mentioned ! It's weird because I remember looking through the npm scripts and can't remember seeing test:unit, dev or lint. CI tests seemed to run fine on my Mac :/ I'll have a look tomorrow then :)

**Comment by gempain** [comment]
@erikbarke Thanks for the helpful Wiki page :) I fixed the lint, and unit tests all pass on my end (11 tests, 11 passed, ok). `npm test` doesn't work but `npm run test:windows` does (all tests show "SUCCESS".

Another remark I would make is that I find the unit test framework a bit unintuitive. I found it hard to understand how to write unit tests (and ended up giving up :( ). Why not use jasmine ? It's quite clear, has spies and I like a lot the describe-it template, which coupled with the `karma-mocha` reporter is great :)

But in the end all I have to say is thank you for this amazing project !

**Comment by gempain** [comment]
@erikbarke I can see that the build has failed again on both CI servers. But honestly, everything works on my end. Clone the PR and test it, you'll see :) I can provide screenshots if needed :) The error shown in the console shows that module `../../shared/confirguration` cannot be found, but this does not seem to be related to my changes. See: 
Unit tests:
units

CI tests are too long for me to post a screenshot :p

**Comment by erikbarke** [comment]
The unit tests fail because they run from the `dist` folder, which you removed in this PR. The dist folder has also been removed from the git repo in PR #190, which hasn't been merged yet, so I'm not quite sure what to do here, maybe I should just merge all these PRs and keep working on them locally.

**Comment by gempain** [comment]
@erikbarke I see :) The reason I deleted the `dist` folder is that build folders should not be part of the repository IMO (and it is a common practice I have seen on 99% of the projects I have worked on. Plus, it lightens the repo :)

The test workflow should build the sources itself. I think the solution here is to just include `npm run buil` and `npm run build:ci` as part of the test scripts. Let me give it a try :)

**Comment by erikbarke** [comment]
- `npm run build` compiles and emits the compiled sources to "dist".
- `npm run build:ci` just compiles without emitting anything.

The way this should be done is running `npm run build` instead of `npm run build:ci` in the .travis.yml and the appveyor.yml files.

**Comment by gempain** [comment]
Sounds good :) Or add pre-scripts ? This way people that run the tests will also have the build made for them. It took me while to realize I actually had to run the build before the test script :)

Seems like we've got one up and running :) Just need to make sure Appveyor is running now.

**Comment by gempain** [comment]
I think we're good to go :smile:

**Comment by mitchhentges** [comment]
> The unit tests fail because they run from the dist folder, which you removed in this PR. The dist folder has also been removed from the git repo in PR #190, which hasn't been merged yet, so I'm not quite sure what to do here, maybe I should just merge all these PRs and keep working on them locally.

IMHO, for the sake of keeping PRs restricted to a single feature/fix, it might be worth it to merge #190, then update this PR with `master` after the merge. That way, it will be as clear as possible what changes this PR will have, and the diff will only include the required changes for #188 

(then again, I might be biased, because I'm looking forward to #190 getting in :wink:)

**Comment by gempain** [comment]
@mitchhentges You're perfectly right ;) thought I think rebase would be better than merge here :)

**Comment by erikbarke** [comment]
Ok guys, since you're both in this thread:

@mitchhentges, your PR:s are merged to the `next` branch now. I've changed some stuff and added a few bug fixes but the `next` branch is stable now and runs without hiccups both locally and on the build servers 😌

@gempain, I've switched to the `next` branch for your PR too and it now has conflicts to resolve, surprise, surprise... I guess the easiest way would be to [revert ](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request) all commits except c8732f9. Your idea in 2b8ca33 would be better off in a separate PR, but we need to discuss first how it should be done since it would affect the build process on the ci servers as well!

**Comment by gempain** [comment]
@erikbarke to close.

**Comment by erikbarke** [comment]
Moved to #194.

**Pull request closed without merging**
