### PR TITLE
fix / improve readability of coverage check logic

### PR DESCRIPTION
**Pull request by vladjerca**
@erikbarke your question in the previous PR stuck with me a bit, this is my attempt at an alternative (hopefully more readable/intuitive approach).

This PR is completely *optional*.

### CODE REVIEW

**Comment by erikbarke** [comment]
@vladjerca, much more intuitive! Great work ☺️

**Comment by vladjerca** [comment]
@erikbarke Do you have an ETA for the next minor patch release by any chance? 😊

**Comment by erikbarke** [comment]
@vladjerca, 5.2.0 is on npm now 🎉

**Comment by vladjerca** [comment]
@erikbarke So cool! 🤟

**Pull request merged**
