### PR TITLE
chore: upgrade to acorn@8.1.0 

### PR DESCRIPTION
**Pull request by vladjerca**
In version [8.0.3](https://github.com/acornjs/acorn/blob/2cceb5ec3aeb98b2dd6958106709d97aa8ab0c04/acorn/CHANGELOG.md#803-2020-10-02):

`Fix a wasteful loop during Parser creation when setting ecmaVersion to "latest".`

### CODE REVIEW

**Comment by vladjerca** [comment]
Might relate to #435

On my end at least when using `karma-typescript` in conjuncition with `karma-typescript-es6-transform`, my tests would lock.

I found out it was locking here: https://github.com/monounity/karma-typescript/blob/2275e190b13b0522536141d682ec3d39cd6e0585/packages/karma-typescript-es6-transform/src/transform.ts#L62

This was caused to to an `acorn` bug which caused the parser to lock when using `latest` as the `ecmaVersion`. I've upgraded `acorn` in all packages and I've tested this locally.

**Comment by erikbarke** [comment]
Haha, "cool" detective work @vladjerca 😃

**Comment by vladjerca** [comment]
@erikbarke any plans to publish any patch that includes this soon-ish? 😅

**Comment by erikbarke** [comment]
Now-ish 🤘 v5.5.1 is on npm now 🚀

**Comment by vladjerca** [comment]
@erikbarke

**Pull request merged**
