### PR TITLE
Add possibility to apply comments for coverage settings in transforms 

### PR DESCRIPTION
**Pull request by Hobart2967**
see https://github.com/monounity/karma-typescript/issues/152

### CODE REVIEW

**Comment by Hobart2967** [comment]
see #152

**Comment by Hobart2967** [comment]
https://github.com/monounity/karma-typescript/issues/152

**Comment by erikbarke** [comment]
This is a much better approach than the one I had in mind, it's simple yet effective 😃
However, it slightly breaks the api contract since the dirty flag now is ignored in some cases. I think the callback should have a new, third parameter: `(error: Error, dirty: boolean, transpile: boolean)`
- the transformed code gets bundled only if the `dirty` flag is set to a truthy value, it doesn't matter if the source code or the transpiled code has been transformed. Data from the callback should be ignored if the `dirty` flag is set to a falsy value.
- the transformed code only gets recompiled if the flag `transpile` is set to a truthy value. To avoid breaking changes, this flag is optional and defaults to true.

So, in your case, the callback would be `error = undefined`, `dirty = true`, `transpile = false`.

Also, for the sake of consistency in the Transforms API I think the `emitOutput` property in the context object should be renamed to `transpiled` and its values should be copied to a new object, otherwise any changes would be made directly on the original object, bypassing the `dirty` flag.

If you don't want to wait for the ci servers to give you a slap on the wrist, just run the linter and the tests locally, the commands are in .travis.yml (*nix) and appveyor.yml (windows) in the root of the project.

My apologies for creating a wall of text here, I'm posting from my phone so it's hard to use the code review tools...

When this pr is done it's gonna be a really nice addition to the Transforms API :tada:

**Comment by erikbarke** [comment]
Are you still working on this PR? If not, I'll merge it as-is and make the suggested modifications myself, just let me know!

**Comment by erikbarke** [comment]
Hey, I've modified the API, it looks like this now:

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        transforms: [
            function(context, callback) {
                if(context.ts) {
                    context.ts.transpiled = "\n/* istanbul ignore next */\n" + context.ts.transpiled;
                    return callback(undefined, true, false);
                }
                return callback(undefined, false);
            }
        ]
    }
}
```

The javascript code is in `context.ts.transpiled` and to avoid a recompile, call the callback with the third flag set to `false`: `callback(undefined, true, false);`.

**Comment by Hobart2967** [comment]
(y) nice! thanks mate!

**Pull request merged**
