### PR TITLE
Feature/relative path 2

### PR DESCRIPTION
**Pull request by gempain**
v2 of #193 :

- Adds relative path to the file interface for the coverage exclude option
- Ignore IDEA directory
- Update `.editorconfig` to prevent diff errors when updating manually `package.json`

### CODE REVIEW

**Comment by erikbarke** [comment]
There are 17 commits and 49 changed files in this new PR, shouldn't there be just one or two commits/changed files? It's really hard to track down what you've done as it is now, I cant merge this... What branch/commit etc did you use as starting point when you forked?

**Comment by mitchhentges** [comment]
Looks like this PR is going into master, but the base should be changed to `next` I think :)

**Comment by erikbarke** [comment]
Much better! I'll merge this when the log4js issue has been sorted out ☺️

**Comment by mitchhentges** [comment]
Looks like a successful build (for some reason?). Might still be worth waiting for the log4js fix, but perhaps since it passed then there can be confidence that there's no regression, and it can be merged if code review is OK?

I'm just excited to get PRs merged, no worries either way :wink:

**Comment by gempain** [comment]
@mitchhentges I should have picked `next` instead of `master` ;) Thanks for pointing this out.

> I'm just excited to get PRs merged, no worries either way :wink:

I am as excited as you are :smile: !

@erikbarke when do you think these PRs will be release ?

**Comment by erikbarke** [comment]
It's in the [3.0.8 milestone](https://github.com/monounity/karma-typescript/milestone/23) which is slated for release on 2017-10-31, but since all issues in this milestone are closed I could probably release v3.0.8 within a few days.

I usually create the milestones with a more or less arbitrary deadline, like a month from the creation date and if there are no issues or PR:s I just move the deadline forward as needed. If the issues pile up in the milestone or if there are severe bugs I release as soon as everything is stable, nothing is written in stone ☺️

**Comment by gempain** [comment]
Sounds good, looking forward to it then :)

**Pull request merged**
