### PR TITLE
Check if the file exists before collecting errors, #226

### PR DESCRIPTION
**Pull request by erikbarke**

### CODE REVIEW

**Comment by Erikvv** [comment]
Not sure what this fixes but this allowed my tests to run.

**Comment by baywet** [comment]
@Erikvv this fixes #226

**Comment by Pickatchu59** [comment]
Hi,
I just installed karma-typescript but I found that it doesn't contain this fix.
When you think that you can create a new tag with this modification ? 
Thx

**Comment by baywet** [comment]
@Pickatchu59 https://github.com/monounity/karma-typescript/milestone/25

**Comment by Pickatchu59** [comment]
@baywet  this what I get trying to install the 3.0.10 : 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for karma-typescript@3.0.10
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ocp'
npm ERR! notarget

**Comment by baywet** [comment]
@Pickatchu59 3.0.10 is not yet out https://www.npmjs.com/package/karma-typescript what I shared with you is a milestone => a plan to have those things completed and published by a certain date.

**Comment by Pickatchu59** [comment]
Ah ok I see :+1:  
thx

**Pull request merged**
