### PR TITLE
Removes "dist" files and gitignores it

### PR DESCRIPTION
**Pull request by mitchhentges**
Currently, whenever a change to `karma-typescript` is made, each file is commited twice: once for its actual source code, and once for the compiled version of the source code.

In the same way that dependencies shouldn't be committed to code repositories, build artifacts should also remain outside the repository.
This also makes diffs easier to manage, because you don't need to sift through build artifacts :)

### CODE REVIEW

**Comment by mitchhentges** [comment]
Note: test that this doesn't break the published `npm` package. Ensure that `dist` is still included for deploys :wink:

**Comment by gempain** [comment]
I see you added `npm run prepare` command, but I cannot find the `prepare` script in `package.json`, whcih you seem not to have modified. Is this normal :) ?

**Comment by mitchhentges** [comment]
There's a couple different `package.json` files in this project, mostly under `examples` and `tests`.
The project that I'm ensuring is `npm run prepare`'d is [this one](https://github.com/mitchhentges/karma-typescript/blob/02964167f54041df066aec55816bdba5155bf875/tests/integration-latest/package.json#L27)

Good eye :)

**Comment by erikbarke** [comment]
The `prepare` command is [executed automatically by npm on npm install](https://docs.npmjs.com/misc/scripts).

**Comment by mitchhentges** [comment]
Ah, weird, when I set up locally, I had run `ci/install.sh` but `bower` hadn't been set up. I'll check again, thanks for the good catch :)

**Comment by gempain** [comment]
My fault sorry I didn't mean to put any doubt here :) !

**Comment by erikbarke** [comment]
No worries ☺️

@mitchhentges, what `npm` version are you running? The `prepare` command was introduced in [npm 4.0.0](https://github.com/npm/npm/releases/tag/v4.0.0).

**Comment by mitchhentges** [comment]
@erikbarke I'm running`v3.10.10`, just confirmed that yeah, `prepare` isn't running automatically before `install` for me (because you're right, it's added in `4.0.0` 😄 )

**Comment by gempain** [comment]
I agree with @mitchhentges. I feel like npm v4 is not yet stable enough to move up to it (but it's a personal opinion).

**Comment by erikbarke** [comment]
And yet the 4.x series constantly nags me about upgrading to the 5.x series...

If reverting to 3.10.10 improves the contributor experience, I'm all for it!

**Comment by gempain** [comment]
You know, it's like iOS harassing you to install every patch version...

**Pull request merged**
