### PR TITLE
Add modules to the global scope so they can be mocked

### PR DESCRIPTION
**Pull request by FreshRob**
First step expose the modules

Second step create an npm package to make it easier to mock a module,.
(tried adding it to karma-typescript and importing into a test however I kept getting issues)

e.g.
https://pastebin.com/ed4UunHs

### CODE REVIEW

**Comment by erikbarke** [comment]
Awesome, merged! Regarding the new npm package, would you like me to add a new repo, for instance `karma-typescript-mocks` to the monounity account with you as a maintainer or would you like to host the repo on your github account?

**Comment by FreshRob** [comment]
@erikbarke I've created the mock here https://github.com/DecisionTechnologies/karma-typescript-mock
If you could publish 3.0.5 that would be great

**Comment by erikbarke** [comment]
Again, awesome!! I'll probably be able to release 3.0.5 next week 😃

**Comment by erikbarke** [comment]
3.0.5 is on npm now!

**Pull request merged**
