### PR TITLE
Fix Build: Don't use nonexistant interface ErrorCallback

### PR DESCRIPTION
**Pull request by mitchhentges**

### CODE REVIEW

**Comment by erikbarke** [comment]
The interface `ErrorCallback` is defined in `node_modules/@types/async/index.d.ts` so I don't removing it is the right way to go. Instead, I think it would be more appropriate adding the build step (`npm run build`) to the `.travis.yml` and the `appveyor.yml` files to fix #190 and #191.

**Comment by mitchhentges** [comment]
Ah, fair enough, wasn't aware that that was on async, thought it was a
custom interface that hadn't been defined.

I'll sort it out shortly

**Comment by mitchhentges** [comment]
Should be gucci now :)

**Comment by mitchhentges** [comment]
@erikbarke Is there anything else that should be done for this PR? I think it does the minimum required to fix the build :)

**Pull request merged**
